### PR TITLE
Create 1603KikakuKakikae

### PR DESCRIPTION
**Pull request by celluloce**
書き換え。

### CODE REVIEW

**Comment by celluloce** [comment]
.project_info{
    width: 700px;
    position: relative;
    top: 0;
    left: 0;
    margin-bottom: 100px;
}

/*背景いじるCSS*/
.haikei{
    width: 600px;
    height: 250px;
    opacity: 0.7;
    position: absolute;
    margin: 50px 0 0 30px;
    border: 2px solid  #00552e;
    border-radius: 30px;        /* CSS3草案 */  
    -webkit-border-radius: 30px;    /* Safari,Google Chrome用 */  
    -moz-border-radius: 30px;   /* Firefox用 */  
    background-image: url("hibiki_motoe.jpg");
    background-repeat: no-repeat;
    background-position-x: center;
    background-size: 300px 
}
/*ちびラボ背景*/
div #description_chibilab .haikei{
    width: 600px;
    height: 400px;
    opacity: 0.7;
    position: absolute;
    margin: 50px 0 0 30px;
    border: 2px solid  #00552e;
    border-radius: 30px;        /* CSS3草案 */  
    -webkit-border-radius: 30px;    /* Safari,Google Chrome用 */  
    -moz-border-radius: 30px;   /* Firefox用 */  
    background-image: url("hibiki_motoe.jpg");
    background-repeat: no-repeat;
    background-position-x: center;
    background-size: 300px 
}
/*地球科学背景*/
div #description_tikyuukagaku .haikei{
    width: 600px;
    height: 300px;
    opacity: 0.7;
    position: absolute;
    margin: 50px 0 0 30px;
    border: 2px solid  #00552e;
    border-radius: 30px;        /* CSS3草案 */  
    -webkit-border-radius: 30px;    /* Safari,Google Chrome用 */  
    -moz-border-radius: 30px;   /* Firefox用 */  
    background-image: url("hibiki_motoe.jpg");
    background-repeat: no-repeat;
    background-position-x: center;
    background-size: 300px 
}

/*背景いじるCSS*/
img{
    position: relative;
    width: 40%;
    left: 30%;
    opacity: 0.5;
}

.project_title{
    background-color: #82ae46;
    width: 450px;
    height: 90px;
    position: relative;
}

div.project_title p{
    text-align:right;
    font-size: 15px
}

table, td, th {
    border: 2px #111111 solid;
}

table {
    border-collapse: collapse;
    border-spacing: 0;
}

div.project_info_introduce{
    position: relative;
    left: 50px
}

.project_info_main{
    width: 500px
}

.project_info_detail{
    position: relative;
    left: 100px;
}

**Comment by yumetodo** [comment]
**Reject.**
なぞのファイルを追加せずにファイルを書き換えること。

**Comment by yumetodo** [comment]
cssは
``/event/2017/event_march/resource``へ

**Comment by yumetodo** [comment]
ああ、訂正。
``/event/2017/event_march/resource/css``へ

**Comment by yumetodo** [comment]
@NishiCell 別途branchを切り直すように。このブランチは捨てるべし

**Pull request closed without merging**
